# fly.toml file generated for cool-darkness-4141 on 2022-10-09T21:55:40-04:00

app = "cool-darkness-4141"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NEXT_PUBLIC_API_URL = "https://api.turboremote.org"
    NEXT_PUBLIC_SENTRY_DSN = "https://f1bc104e413443d5b798a1a218178c18@o4503995969241088.ingest.sentry.io/4503995974483968"
    NEXT_PUBLIC_SENTRY_ENV = "production"
    NEXT_PUBLIC_GA_TRACKING_ID = "G-CGWG7YEQBY"

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
